# Generated by Django 6.0.7 on 2026-07-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='BIOGRAPHY',
            new_name='biography',
        ),
    ]
